source 'http://rubygems.org'
source "http://gems.undev.cc"

gem 'rails'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'pg'

group :assets do
  gem 'uglifier'
  gem "therubyracer"
  gem 'sass-rails'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'haml-rails'
gem 'russian'
gem 'kaminari'
gem 'rmagick'
gem 'carrierwave'
gem 'twitter-bootstrap-rails'
gem 'simple_form'
gem 'cocoon'
gem 'state_machine'
gem 'validates'
gem 'backup'
gem 'configus'
gem "ckeditor"
gem 'mini_magick'
gem 'usefull_scopes', :git => 'git://github.com/kaize/usefull_scopes.git'
gem 'capi'
gem "meta_search"
gem 'gritter'
gem 'draper'
gem 'js-routes'
gem 'gon'
gem 'jbuilder'

group :development do
  gem 'erb2haml'
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'capistrano_colors'
  gem 'rvm-capistrano'
  gem 'factory_girl_rails'
end

group :test do
  gem 'simplecov', :require => false
  gem 'ci_reporter'
  gem 'minitest'
  gem 'factory_girl'
  gem 'turn'
  gem 'tconsole'
end

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
gem 'unicorn'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
